### ISSUE TITLE
Use Cases?

### ISSUE THREAD

**Issue by colemickens** [Arnavion/k8s-openapi-codegen#17]
Hi, this repo is very interesting to me as someone interested in Kubernetes and Rust. I stumbled across it a couple days ago with a random page of "kubernetes rust" search results, and then just came across you in the `minikube` repo as well.

May I be nosy? What is your use-case or planned use for this? Are you planning to write clients/controllers/random utils with it?

I'd be curious if you've thought about being able to define models in Rust and emit CRDs or custom API object definitions? Or maybe that's more appropriate for a separate repo/gen-tool?

**Comment by Arnavion** [comment]
>What is your use-case or planned use for this? Are you planning to write clients/controllers/random utils with it?

I'm personally not planning to do much with it. I had initially started this because I might have needed it for a work project, but that is not the case any more. At any rate I will continue working on it in my free time for now.

Yes, the use case is to be the equivalent of kubernetes/api and kubernetes/client-go for Rust. So you'd use it to write both external client applications to interface with a k8s cluster, and operators or controllers that run within the cluster.

>I'd be curious if you've thought about being able to define models in Rust and emit CRDs or custom API object definitions? Or maybe that's more appropriate for a separate repo/gen-tool?

If you want to use this crate directly, you can see the k8s-openapi-tests directory for an example. There is a CRD example there also that shows how you'd define and register your own CRD type, and create CRs of that type.

But yes, the API provided by this crate is rough and not very Rust-like. My expection is that repos like anowell/kubeclient-rs will use this crate and layer a more Rust-like API on top. See https://github.com/anowell/kubeclient-rs/issues/4 for discussion about that. I don't think I would want *this* crate to do any fixups to the generated code (apart from what it does to work around mistakes in the spec, of course).
