### ISSUE TITLE
[Question] Difference with kubernetes-client/gen

### ISSUE THREAD

**Issue by ngortheone** [Arnavion/k8s-openapi-codegen#26]
Hi @Arnavion 
As I was exploring available options for kubernetes clients for rust I found out that @ynqa in his  https://github.com/ynqa/kubernetes-rust/pull/10 is moving away from your library and tries to use https://github.com/kubernetes-client/gen

On the surface it seems like reinvention of the wheel, so I decided find out if there is substantial difference between kubernetes-client/gen and your approach and why kubernetes-client/gen might not want to accept a client that was not generated with their generator.

I believe that you did some kind of research before writing your own generator, so there must  reason for that. Could you please share your perspective?

**Comment by Arnavion** [comment]
Most of the differences amount to this crate doing things specific to Kubernetes's OpenAPI spec that a generic swagger generator does not.

Almost everything in https://github.com/Arnavion/k8s-openapi-codegen/blob/15777b259ac16cc4287da3ede50f62d3c4508be9/src/fixups.rs is what an automatic swagger-generated client gets wrong. You don't have to read the code, just read the comments.

-  Some of these are fixed in new versions of the OpenAPI spec in upstream so they only apply to older versions, which is why you won't find the mistake in that PR's generated code. But this repo generates specs for older versions too so it needs them. I'm not sure what that crate's policy will be to generate clients for older versions of Kubernetes.

- Kubernetes uses `x-kubernetes-*` annotations to annotate the APIs in the spec and this crate uses them to make the API as inherent methods of the corresponding struct, like [`Pod::list_core_v1_namespaced_pod`.](https://github.com/Arnavion/k8s-openapi-codegen/blob/15777b259ac16cc4287da3ede50f62d3c4508be9/k8s-openapi/src/v1_13/api/core/v1/pod.rs#L1770) The swagger-generated specs don't do this, so they put all API in [giant top-level traits.](https://github.com/ynqa/kubernetes-rust/blob/9d38e6eb0f506c0bd12538164ac822923650816b/kubernetes-apis/src/apis/core_v1_api.rs#L30)

- The OpenAPI spec has a lot of typedefs under the `io.k8s.kubernetes.pkg` namespace, which was where the types originally lived in v1.7 and are now just kept for backwards-compatibility. The code generated by that PR [handles them badly.](https://github.com/ynqa/kubernetes-rust/blob/9d38e6eb0f506c0bd12538164ac822923650816b/kubernetes-apis/src/models/io_k8s_kubernetes_pkg_api_v1_affinity.rs) This crate [just ignores them.](https://github.com/Arnavion/k8s-openapi-codegen/blob/15777b259ac16cc4287da3ede50f62d3c4508be9/src/fixups.rs#L339-L341)

- The very first diff at https://github.com/ynqa/kubernetes-rust/pull/10/files#diff-04c6e90faac2675aa89e2176d2eec7d8R26 suggests to me that that generated client isn't taking optional parameters into account properly, given that it requires the caller to pass in `""` and `1` instead of `None`. Also note that the next release of *this* crate will remove the need to pass in so many explicit `None` for optional parameters, [since these have now been moved to a separate `Default`-able struct.](https://github.com/Arnavion/k8s-openapi-codegen/commit/bbbc770a9be50159decffc098bf2d88fa933ef1c)

- Most importantly, the APIs generated in that PR are all synchronous, since they're all functions that take parameters and return `Result<Response>`, and [internally use `reqwest::Client`.](https://github.com/ynqa/kubernetes-rust/blob/9d38e6eb0f506c0bd12538164ac822923650816b/kubernetes-apis/src/apis/configuration.rs#L17) AFAIK the swagger generator is configurable in this regard, since I remember one of the other swagger-generated Kubernetes clients on crates.io is asynchronous (uses `hyper::Client` internally).

  But neither of these options is good in my eyes since I would like the user to use whatever they want, which is why the API generated by *this* crate uses [the sans-io approach](https://github.com/Arnavion/k8s-openapi-codegen/blob/15777b259ac16cc4287da3ede50f62d3c4508be9/k8s-openapi/src/lib.rs#L140-L142) which was [popularized by Python.](https://sans-io.readthedocs.io/)

**Comment by ngortheone** [comment]
Thanks for a very detailed answer!

Does it mean that as official kubernetes-client/gen will get better at handling those issues this repo/crate will become obsolete? (Is there a chance that official gen will become better?)

Separately
Would you be interested in a PR with enhancements to  readme/docs with this information, and information that I can find in other issues ?( e.g. intended usage :
https://github.com/Arnavion/k8s-openapi-codegen/issues/20
https://github.com/Arnavion/k8s-openapi-codegen/issues/24
https://github.com/Arnavion/k8s-openapi-codegen/issues/17
)
